// recipe.http
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNTYyODI2LCJleHAiOjE3NjA1NjM0MjZ9.jzGYo0ZbZ9NoP4QVZkSdkKY_00C5cCD5GXPnRQ9d1og
@baseUrl = http://localhost:3000

### ========== PUBLIC ==========

### List recipes (PUBLIC)
GET {{baseUrl}}/api/recipe/public

### Get recipe by ID (PUBLIC)
GET {{baseUrl}}/api/recipe/public/4

### Create recipe (PUBLIC)
POST {{baseUrl}}/api/recipe/public
Content-Type: application/json

{
  "customerId": 2,
  "issuedAt": "2025-10-10T14:00:00Z",
  "notes": "Take with food",
  "status": "VALID"
}

### Update recipe (PUBLIC)
PATCH {{baseUrl}}/api/recipe/public/4
Content-Type: application/json

{
  "notes": "Updated instructions",
  "status": "VALID"
}

### Hard delete recipe (PUBLIC)
DELETE {{baseUrl}}/api/recipe/public/1

### Soft delete recipe (PUBLIC)
DELETE {{baseUrl}}/api/recipe/public/4/logic


### ========== AUTHENTICATED ==========

### List recipes (AUTH)
GET {{baseUrl}}/api/recipe
Authorization: Bearer {{token}}

### Get recipe by ID (AUTH)
GET {{baseUrl}}/api/recipe/5
Authorization: Bearer {{token}}

### Create recipe (AUTH)
POST {{baseUrl}}/api/recipe
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "customerId": 4,
  "issuedAt": "2025-10-10T14:00:00Z",
  "notes": "Take with food",
  "status": "VALID"
}

### Update recipe (AUTH)
PATCH {{baseUrl}}/api/recipe/54
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "notes": "Updated instructions",
  "status": "VALID"
}

### Hard delete recipe (AUTH)
DELETE {{baseUrl}}/api/recipe/5
Authorization: Bearer {{token}}

### Soft delete recipe (AUTH)
DELETE {{baseUrl}}/api/recipe/9/logic
Authorization: Bearer {{token}}
