// payment.http
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNTYyODI2LCJleHAiOjE3NjA1NjM0MjZ9.jzGYo0ZbZ9NoP4QVZkSdkKY_00C5cCD5GXPnRQ9d1og
@baseUrl = http://localhost:3000

### ========== PUBLIC ==========

### List payments (PUBLIC)
GET {{baseUrl}}/api/payment/public

### Get payment by ID (PUBLIC)
GET {{baseUrl}}/api/payment/public/1

### Create payment (PUBLIC)
POST {{baseUrl}}/api/payment/public
Content-Type: application/json

{
  "saleId": 3,
  "amount": 24800,
  "method": "CARD",
  "paidAt": "2025-10-11T16:25:00Z",
  "status": "PAID",
  "reference": "TRX-123456"
}

### Update payment (PUBLIC)
PATCH {{baseUrl}}/api/payment/public/5
Content-Type: application/json

{
  "status": "REFUNDED",
  "reference": "REF-98765"
}

### Hard delete payment (PUBLIC)
DELETE {{baseUrl}}/api/payment/public/3

### Soft delete payment (PUBLIC)
DELETE {{baseUrl}}/api/payment/public/5/logic


### ========== AUTHENTICATED ==========

### List payments (AUTH)
GET {{baseUrl}}/api/payment
Authorization: Bearer {{token}}

### Get payment by ID (AUTH)
GET {{baseUrl}}/api/payment/5
Authorization: Bearer {{token}}

### Create payment (AUTH)
POST {{baseUrl}}/api/payment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "saleId": 6,
  "amount": 23800,
  "method": "CARD",
  "paidAt": "2025-10-11T16:25:00Z",
  "status": "PAID",
  "reference": "TRX-123456"
}

### Update payment (AUTH)
PATCH {{baseUrl}}/api/payment/73
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "REFUNDED",
  "reference": "REF-98765"
}

### Hard delete payment (AUTH)
DELETE {{baseUrl}}/api/payment/5
Authorization: Bearer {{token}}

### Soft delete payment (AUTH)
DELETE {{baseUrl}}/api/payment/73/logic
Authorization: Bearer {{token}}
